version: '3'
volumes:
  data:
  minio_data:
services:
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}      
    volumes:
      - data:/var/lib/mysql
    ports:
      - "3306:3306"

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SQLALCHEMY_DATABASE_URI: mysql+pymysql://${MYSQL_USER}:${MYSQL_PASSWORD}@db:3306/${MYSQL_DATABASE}
      TEST_SQLALCHEMY_DATABASE_URI: mysql+pymysql://${MYSQL_USER}:${MYSQL_PASSWORD}@db:3306/${MYSQL_DATABASE}
      SECRET_KEY: ${SECRET_KEY}
      JWT_SECRET: ${JWT_SECRET}
      JWT_ALGORITHM: ${JWT_ALGORITHM}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      MINIO_BUCKET_NAME: ${MINIO_BUCKET_NAME}
      MINIO_HOSTNAME: minio:9000
    command: 
      - /bin/bash
      - -c
      - |
        sleep 30
        python3 /app/manager.py --init-db
        uvicorn manager:app --reload --host 0.0.0.0 --port 8010
    ports:
      - "8010:8010"
    depends_on:
      - db
  minio:
    image: minio/minio
    # command: server /data
    hostname: minio
    command: minio server --console-address ":9090" /data
    ports:
      - ,:9000
      - 9090:9090        
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}

    # ports:
    #   - "9000:9000"
    #   - "9001:9001"

    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9090/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
